<a href="https://colab.research.google.com/github/JuanZapa7a/Hello-world/blob/readme-edits/Ajuste_de_imagen.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# 9. Ajuste de Imagen: Transformación del Contenido de la Imagen
## 9.1. Manipulación de Color

La mayoría de las funciones para manipular los canales de color se encuentran en el submódulo skimage.color.
### 9.1.1. Conversión entre modelos de color

Las imágenes a color pueden representarse utilizando diferentes espacios de color. Uno de los espacios de color más comunes es el espacio RGB, donde una imagen tiene canales de rojo, verde y azul. Sin embargo, se utilizan ampliamente otros modelos de color, como el modelo de color HSV, donde el tono, la saturación y el valor son canales independientes, o el modelo CMYK utilizado para la impresión.

skimage.color proporciona funciones de utilidad para convertir imágenes hacia y desde diferentes espacios de color. Los arreglos de tipo entero pueden transformarse a tipo de punto flotante mediante la operación de conversión.

In [5]:
import numpy as np
from skimage import color

In [6]:
# Rojo brillante saturado
pixel_rojo_rgb = np.array([[[255, 0, 0]]], dtype=np.uint8)
color.rgb2hsv(pixel_rojo_rgb)


array([[[0., 1., 1.]]])

In [7]:
# Azul saturado más oscuro
pixel_azul_oscuro_rgb = np.array([[[0, 0, 100]]], dtype=np.uint8)
color.rgb2hsv(pixel_azul_oscuro_rgb)


array([[[0.66666667, 1.        , 0.39215686]]])

In [8]:
# Rosa menos saturado
pixel_rosa_rgb = np.array([[[255, 100, 255]]], dtype=np.uint8)
color.rgb2hsv(pixel_rosa_rgb)



array([[[0.83333333, 0.60784314, 1.        ]]])